# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Pipiline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build_backend:
    name: Build_backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: backend/demo

    - name: Upload resulting Build package
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: backend/demo/target
  BE-docker-image-delivery:
    name: BE Docker Image Delivery
    runs-on: ubuntu-latest
    needs: Build_backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: Package
          path: backend/demo/target/
      
      - name: Generate image tag
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"

      - name: Docker build
        run: docker build -t mihaprah/backend:$TAG_NAME -f backend/demo/src/main/docker/Dockerfile.jvm ./backend/demo
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date}}

      - name: Retag to latest
        run: docker tag mihaprah/backend:$TAG_NAME mihaprah/backend:latest
        env:
          TAG_NAME: CD-&{{ steps.date.outputs.date }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Docker push
        run: docker push mihaprah/backend:$TAG_NAME && docker push mihaprah/backend:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}
